apiVersion: v1
kind: Pod
metadata:
  name: opa-disallowed
  labels:
    owner: me.agilebank.demo
spec:
  securityContext:
     fsGroup: 150
  containers:
    - name: opa
      image: openpolicyagent/opa:0.9.2
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"
      securityContext:
          capabilities:
            add: [""]
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
