---
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: gatekeeper-system
  labels:
    {{- include "constrainttemplates.labels" . | nindent 4 }}
spec:
  match:
  - excludedNamespaces:
    {{- range $ns := .Values.policy_controller_exemptable_namespaces }}
    - {{ $ns }}
    {{- end }}
    processes:
    - '*'
