apiVersion: v1
kind: Pod
metadata:
  name: nginx-host-networking-ports-disallowed
  labels:
    app: nginx-host-networking-ports
spec:
  securityContext:
    fsGroup: 200
  hostNetwork: true
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 9001
      hostPort: 9001
    securityContext:
      capabilities:
        drop: ["KILL", "MKNOD", "SYS_CHROOT"]
