apiVersion: v1
kind: Pod
metadata:
  name: fsgroup-allowed
  labels:
    app: nginx-users
spec:
  securityContext:
    fsGroup: 200
#      rule: MustRunAs
  containers:
    - name: nginx
      image: nginx
      securityContext:
        capabilities:
          drop: ["KILL", "MKNOD", "SYS_CHROOT"]
