apiVersion: v1
kind: Pod
metadata:
  name: nginx-host-namespace-allowed
  labels:
    app: nginx-host-namespace
spec:
  securityContext:
     fsGroup: 150
     #Rule: MustRunAs
  hostPID: false
  hostIPC: false
  containers:
  - name: nginx
    image: nginx
    securityContext:
        capabilities:
          drop: ["KILL", "MKNOD", "SYS_CHROOT"]
