apiVersion: v1
kind: Pod
metadata:
  name: nginx-host-namespace-disallowed
  labels:
    app: nginx-host-namespace
spec:
  securityContext:
     fsGroup: 150
     #Rule: MustRunAs
  hostPID: true
  hostIPC: true
  containers:
  - name: nginx
    image: nginx
    securityContext:
      capabilities:
        drop: ["KILL", "MKNOD", "SYS_CHROOT"]
