apiVersion: v1
kind: Service
metadata:
  name: my-lb-service-disallowed
  #namespace: test
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
#  clusterIP: <>
  type: LoadBalancer
