apiVersion: v1
kind: Pod
metadata:
  name: nginx-privileged-allowed
  labels:
    app: nginx-privileged
spec:
  securityContext:
    fsGroup: 200
  containers:
  - name: nginx
    image: nginx
    securityContext:
      privileged: false
      capabilities:
        drop: ["KILL", "MKNOD", "SYS_CHROOT"]
