apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume-types-allowed
  labels:
    app: nginx-volume-types
spec:
  securityContext:
     fsGroup: 150
  containers:
  - name: nginx
    image: nginx
    securityContext:
      capabilities:
        drop: ["KILL", "MKNOD", "SYS_CHROOT"]
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  - name: nginx2
    image: nginx
    securityContext:
      capabilities:
        drop: ["KILL", "MKNOD", "SYS_CHROOT"]
    volumeMounts:
    - mountPath: /cache2
      name: demo-vol
  volumes:
  - name: cache-volume
    emptyDir: {}
  - name: demo-vol
    emptyDir: {}
