apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume-types-disallowed
  labels:
    app: nginx-volume-types
spec:
  securityContext:
     fsGroup: 150
  containers:
  - name: nginx
    image: nginx
    securityContext:
      capabilities:
        drop: ["KILL", "MKNOD", "SYS_CHROOT"]
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  - name: nginx2
    image: nginx
    volumeMounts:
    - mountPath: /cache2
      name: demo-vol
    securityContext:
      capabilities:
        drop: ["KILL", "MKNOD", "SYS_CHROOT"]
  volumes:
  - name: cache-volume
    nfs:
      server: nfs-server.default.svc.cluster.local
      path: "/"
    #hostPath:
    #  path: /tmp # directory location on host
  - name: demo-vol
    downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
